### ISSUE TITLE
"Copy link" buttons

### ISSUE THREAD

**Issue by JohnNelsonMaps** [Esri/imagery-explorer-apps#14]
in order to make copying a URL to the app in a specific state as clear and easy as possible, let's add a copy link button to the map's nav button list and to the animation UI. clicking either of these buttons adds the current URL to the clipboard.

**Map nav button group**
- a "copy link" button is available below the "snapshot" button.
- use the [link](https://developers.arcgis.com/calcite-design-system/icons/?icon=link&query=link) calcite icon
- tooltip: "Copy link to this app in its current state."
- on click, a success message appears to the right of the button: "([check](https://developers.arcgis.com/calcite-design-system/icons/?icon=check&query=check) icon) Link copied to clipboard."
- the success message appears for 3 seconds, then fades away.

![image](https://github.com/Esri/imagery-explorer-apps/assets/126284417/827e1962-5974-407d-abad-18b0fcc066ab)
![image](https://github.com/Esri/imagery-explorer-apps/assets/126284417/5dbc4ecc-9c8f-40a7-89a9-841ba244e734)

**Animation UI**
Because we hide much of the UI during animation mode, let's add the copy link button to the animation panels as well.
- same link icon as the map nav button.
- in the animation panel, placed to the left of the download button. there is limited space here so Jinnan will experiment with resizing buttons to make room. if it doesn't fit we can discuss a plan B.
- in the animation's close/download panel in the top-right of the map, add a link button to the left of the download button. This will require that the diagonal background gradient be enlarged to accommodate the third button. Ideally the three buttons (copy link, download, and close) get a black dropshadow to increase visibility.
- clicking the copy link button (in the animation button panel or the top right panel) shows a message in the same place as the download animation messages: "Animation link copied to clipboard."
- the success message appears for 3 seconds, then fades away.

here's a bad mockup on the top right panel with the link button:
![image](https://github.com/Esri/imagery-explorer-apps/assets/126284417/c702d1b6-8497-4948-8011-c1d2d6aa5a29)
and the message
![image](https://github.com/Esri/imagery-explorer-apps/assets/126284417/e3cb15ab-e556-4f45-8254-b1c941b17c02)

**Comment by vannizhang** [comment]
@JohnNelsonMaps added Cop Link Button to Map action buttons group. Please test on DEV.

**Comment by JohnNelsonMaps** [comment]
map nav group's _copy link_ button confirmed on dev. Nice!
