### ISSUE TITLE
Scene selection in landsat

### ISSUE THREAD

**Issue by Dhaya22** [Esri/imagery-explorer-apps#15]
<img width="958" alt="Screenshot 2024-03-29 110608" src="https://github.com/Esri/imagery-explorer-apps/assets/100189551/a56c330f-ba14-45a1-94d2-b38fcff4786c">
After i download the repository and tried to host it in the local server,I couldn't see any imagery dates during the scene selection.It gives **code: 403, messageCode: 'GWM_0003', message: 'You do not have permissions to access this resource or perform this operation.', details: Array(0)**} error in the console.

**Comment by vannizhang** [comment]
HI @Dhaya22, please checkout this [section](https://github.com/Esri/imagery-explorer-apps?tab=readme-ov-file#usage) of the README. You will need to update the `config.json` to use your own proxy service of Landsat Level-2 service, you can check this [Add an ArcGIS Server web service](https://doc.arcgis.com/en/arcgis-online/create-maps/add-layers-from-url.htm#ESRI_SECTION1_F5DDFE50C13245D8BF09A78E8802B4D9) page if you don't know how to create the proxy service.
