### ISSUE TITLE
timeline list auto-scroll

### ISSUE THREAD

**Issue by JohnNelsonMaps** [Esri/imagery-explorer-apps#4]
When clicking through the images of an animation list, the list will auto-scroll to the bottom, making it hard to explore the list or click through the images in sequence. It makes sense to jump to the bottom of the list when adding new images, but ideally it wouldn't auto-scroll on list-item selection.

**Comment by vannizhang** [comment]
@JohnNelsonMaps please review this fix on DEV.

**Comment by JohnNelsonMaps** [comment]
confirmed on dev. looks great!
