### ISSUE TITLE
Calcite accessibility selection graphic returned

### ISSUE THREAD

**Issue by JohnNelsonMaps** [Esri/imagery-explorer-apps#5]
Probably due to a change to the underlying calcite stuff, the visually intrusive accessibility selection graphic is back on the swipe widget. I disagree with the accessibility benefit this provides and recommend hiding it.
![image](https://github.com/Esri/imagery-explorer-apps/assets/126284417/3f2afd7e-6c4b-4613-ad70-7a3bd6c2e541)

**Comment by vannizhang** [comment]
@JohnNelsonMaps please review this fix on DEV.
