### ISSUE TITLE
Collapse citations/credits to compact version by default

### ISSUE THREAD

**Issue by robert-waterman** [Esri/imagery-explorer-apps#7]
Default compact citation/credit should be: "Powered by Esri | Landsat imagery courtesy of USGS, NASA, and Microsoft"

Full attribution shown upon hover over.

**Comment by vannizhang** [comment]
@robert-waterman please review this fix on DEV.

**Comment by robert-waterman** [comment]
@vannizhang , verified fixed. Please close after you push to prod.
